name: Performance

on: [push]
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  perf:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Get sources
      uses: actions/checkout@v2

    - name: Run npm install
      run: npm install --no-package-lock --no-audit --no-fund

    - name: Build repos
      run: npm run build:repos

    - name: Start react app
      run: npm run start:react:prod &

    - name: Start vue app
      run: npm run start:vue:prod &

    - name: Run tests
      run: npm run test

    - name: Copy artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: ${{ github.workspace }}/*.log
        if-no-files-found: ignore